<a href="https://colab.research.google.com/github/hwelti/Math-242/blob/main/Gram_Schmidt_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

In [8]:
#Create a Vector
r1 = np.matrix([[3],[0],[3],[0]])
r1 = np.array([3,0,3,0])

r1

#Vector Arithmatic
r1*3


array([9, 0, 9, 0])

In [6]:
r1.dot(r1)

18

#Gram Schmidt Orthonormalization Process

We'll use the Gram-Schmidt process to find the orthonormal vectors in $R^4$

## Our "Random Vectors"

In [13]:
r1 = np.array([3,0,3,0])
r2 = np.array([3,2,3,3])
r3 = np.array([-7,-4,-5,-6])
r4 = np.array([-7,-3,-11,2])


##Process $r_1$ 

In [10]:
#Choose the vector and subtract off the "nice" orthagonal pieces:
t1=r1
#t1

#Normalize t1:
m=np.sqrt((t1.dot(t1)))

#Create the Orthagonal Vector
u1=t1*1/m

print(u1)

[0.70710678 0.         0.70710678 0.        ]


##Process $r_2$

In [18]:
#Choose the vector and subtract off the "nice" orthagonal pieces:
t2=r2 - ((u1.dot(r2))*u1)
#t1

#Normalize t2:
m=np.sqrt((t2.dot(t2)))

#Create the Orthagonal Vector
u2=t2*1/m

print(u2)

[-1.23168186e-16  5.54700196e-01 -1.23168186e-16  8.32050294e-01]


In [ ]:
# esentially: [0, 0.55,0,0.83]
#Should be [0,2/sqrt(13),0,3/sqrt(13)]

##Process $r_3$


In [19]:
#Choose the vector and subtract off the "nice" orthagonal pieces:
t3=r3 - ((u1.dot(r3))*u1)-((u2.dot(r3))*u2)
#t1

#Normalize t3:
m=np.sqrt((t3.dot(t3)))

#Create the Orthagonal Vector
u3=t3*1/m

print(u3)

[-7.07106781e-01 -3.14018492e-16  7.07106781e-01 -6.28036983e-16]


##Process $r_4$

In [20]:
#Choose the vector and subtract off the "nice" orthagonal pieces:
t4=r4 - ((u1.dot(r4))*u1)-((u2.dot(r4))*u2)-((u3.dot(r4))*u3)
#t1

#Normalize t4:
m=np.sqrt((t4.dot(t4)))

#Create the Orthagonal Vector
u4=t4*1/m

print(u4)

[ 0.         -0.83205029  0.          0.5547002 ]
